name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install, lint and test
        run: |
          npm install
          npm run lint
          npm run test
